// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package database

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, user_id) 
VALUES (?, ?) 
RETURNING id, user_id, name, created_at, updated_at, deleted_at, deleted_reason
`

type CreateAccountParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE name = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, name)
	return err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, user_id, name, created_at, updated_at, deleted_at, deleted_reason 
FROM accounts
WHERE name = ?
`

func (q *Queries) GetAccountByName(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByName, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
	)
	return i, err
}
