// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, is_income) 
VALUES (?, ?) 
RETURNING id, name, is_income, created_at, updated_at, deleted_at, deleted_reason
`

type CreateCategoryParams struct {
	Name     string
	IsIncome bool
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.IsIncome)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsIncome,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories 
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, is_income, created_at, updated_at, deleted_at, deleted_reason 
FROM categories
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsIncome,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByType = `-- name: GetCategoriesByType :many
SELECT id, name, is_income, created_at, updated_at, deleted_at, deleted_reason 
FROM categories
WHERE is_income = ?
`

func (q *Queries) GetCategoriesByType(ctx context.Context, isIncome bool) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByType, isIncome)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsIncome,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const txnsByCategory = `-- name: TxnsByCategory :many
SELECT c.name, SUM(t.amount) AS total
FROM users u 
	JOIN accounts a ON a.user_id = u.id 
	JOIN transactions t ON t.account_id = a.id
	JOIN category_transaction ct ON ct.transaction_id = t.id
	JOIN categories c on ct.category_id = c.id 
WHERE u.name = ? 
	AND t.occurred_at >= ? 
	AND t.occurred_at <= ?
	AND c.is_income = ?
GROUP BY c.name
`

type TxnsByCategoryParams struct {
	Name         string
	OccurredAt   int64
	OccurredAt_2 int64
	IsIncome     bool
}

type TxnsByCategoryRow struct {
	Name  string
	Total sql.NullFloat64
}

func (q *Queries) TxnsByCategory(ctx context.Context, arg TxnsByCategoryParams) ([]TxnsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, txnsByCategory,
		arg.Name,
		arg.OccurredAt,
		arg.OccurredAt_2,
		arg.IsIncome,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TxnsByCategoryRow
	for rows.Next() {
		var i TxnsByCategoryRow
		if err := rows.Scan(&i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
