// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Account struct {
	ID            int64
	UserID        int64
	Name          string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     sql.NullString
	DeletedReason sql.NullString
}

type Transaction struct {
	ID            int64
	AccountID     int64
	IsIncome      bool
	Amount        float64
	Description   string
	OccurredAt    string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     sql.NullString
	DeletedReason sql.NullString
}

type User struct {
	ID            int64
	Name          string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     sql.NullString
	DeletedReason sql.NullString
}
