// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Account struct {
	ID            int64
	UserID        int64
	Name          string
	CreatedAt     int64
	UpdatedAt     int64
	DeletedAt     sql.NullInt64
	DeletedReason sql.NullString
}

type Category struct {
	ID            int64
	Name          string
	IsIncome      bool
	CreatedAt     int64
	UpdatedAt     int64
	DeletedAt     sql.NullInt64
	DeletedReason sql.NullString
}

type CategoryTransaction struct {
	TransactionID int64
	CategoryID    int64
}

type Session struct {
	ID         int64
	Username   sql.NullString
	LastOpened int64
}

type Transaction struct {
	ID            int64
	AccountID     int64
	IsIncome      bool
	Amount        float64
	Description   string
	OccurredAt    int64
	CreatedAt     int64
	UpdatedAt     int64
	DeletedAt     sql.NullInt64
	DeletedReason sql.NullString
}

type User struct {
	ID            int64
	Name          string
	CreatedAt     int64
	UpdatedAt     int64
	DeletedAt     sql.NullInt64
	DeletedReason sql.NullString
	Theme         interface{}
}
