// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package database

import (
	"context"
	"database/sql"
)

const loadSession = `-- name: LoadSession :one
SELECT username
FROM session
`

func (q *Queries) LoadSession(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, loadSession)
	var username sql.NullString
	err := row.Scan(&username)
	return username, err
}

const loginSession = `-- name: LoginSession :exec
UPDATE session
SET username = ?1, last_opened = (strftime('%s', 'now'))
WHERE id = 1
`

func (q *Queries) LoginSession(ctx context.Context, username sql.NullString) error {
	_, err := q.db.ExecContext(ctx, loginSession, username)
	return err
}

const logoutSession = `-- name: LogoutSession :exec
UPDATE session
SET username = NULL
WHERE id = 1
`

func (q *Queries) LogoutSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, logoutSession)
	return err
}

const updateSessionLastOpened = `-- name: UpdateSessionLastOpened :exec
UPDATE session
SET last_opened = (strftime('%s', 'now'))
WHERE id = 1
`

func (q *Queries) UpdateSessionLastOpened(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastOpened)
	return err
}
