// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package database

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
	account_id,
	is_income,
	amount,
	description,
	occurred_at
) VALUES (?, ?, ?, ?, ?) 
RETURNING id, account_id, is_income, amount, description, occurred_at, created_at, updated_at, deleted_at, deleted_reason
`

type CreateTransactionParams struct {
	AccountID   int64
	IsIncome    bool
	Amount      float64
	Description string
	OccurredAt  string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.AccountID,
		arg.IsIncome,
		arg.Amount,
		arg.Description,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IsIncome,
		&i.Amount,
		&i.Description,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}
