// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name) 
VALUES (?) 
RETURNING id, name, created_at, updated_at, deleted_at, deleted_reason
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
	)
	return i, err
}

const deleteAccountByName = `-- name: DeleteAccountByName :exec
DELETE FROM users 
WHERE name = ?
`

func (q *Queries) DeleteAccountByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountByName, name)
	return err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, created_at, updated_at, deleted_at, deleted_reason 
FROM users 
WHERE name = ?
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
	)
	return i, err
}
