// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name) 
VALUES (?) 
RETURNING id, name, created_at, updated_at, deleted_at, deleted_reason, theme
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
		&i.Theme,
	)
	return i, err
}

const deleteAccountByName = `-- name: DeleteAccountByName :exec
DELETE FROM users 
WHERE name = ?
`

func (q *Queries) DeleteAccountByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountByName, name)
	return err
}

const getAllUserNames = `-- name: GetAllUserNames :many
SELECT name 
FROM users
`

func (q *Queries) GetAllUserNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, created_at, updated_at, deleted_at, deleted_reason, theme 
FROM users 
WHERE name = ?
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedReason,
		&i.Theme,
	)
	return i, err
}
